### PR TITLE
Testable undo redo error modal

### PR DESCRIPTION
**Pull request by chrispymm**
Adds a pretty generic error message in a modal that is displayed if an undo or a redo action fails to complete.

If the action fails, its likely due to an issue with the metadata, and retrying the action is unlikely to succeed so we remove the button on failure.

### CODE REVIEW

**Review by H3ll3m4 — DISMISSED** [review]
🚀

**Comment by njseeto** [comment]
Do we have any / do we want to add any acceptance tests for these new modals?

**Comment by chrispymm** [comment]
> Do we have any / do we want to add any acceptance tests for these new modals?

We don't, and we probably should.  I'll add a couple. 👍

**Review by njseeto — APPROVED** [review]
🚀

**Pull request merged**
