### PR TITLE
Improve branch edit page performance

### PR DESCRIPTION
**Pull request by StevenLeighton21**
The edit branch page was having performance issues when loading very large forms, this change should drastically reduce the number of objects allocated when rendering the partials for the edit page.

Previously, the conditionals partial would traverse all possible flows _for each_ conditional, to generate a new list of destinations and detached destinations, for each branch, plus the 'otherwise' dropdown.

This results in ~18 million object allocations to render the edit form over about 15 seconds
image

The change moves the `@branch.destinations` and `@branch.detached_destinations` into a helper method on the controller (so all the partials such as when adding a new conditional) can access a cached-in-memory list of destinations.

This cuts us down to around 3.5 million allocations (in the very large test form) over about 4 seconds
image

There's still a noticeable jump in allocations when detached pages with branches are present (3 million of the 3.5) but that is an investigation for another PR!

### CODE REVIEW

**Review by njseeto — APPROVED** [review]
🚀

**Comment by StevenLeighton21** [comment]
image
testable editor loading the problem page - no longer errors on realistic hardware 👍

**Comment by StevenLeighton21** [comment]
```
I, [2023-01-31T11:27:24.483700 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Started GET "/services/bfc28b70-6f1f-4a93-b3bb-9b0447ea1ff3/branches/4d86bc56-c477-4c64-9f23-6c3734278398/edit" for 35.176.93.186 at 2023-01-31 11:27:24 +0000
I, [2023-01-31T11:27:24.485158 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Processing by BranchesController#edit as HTML
I, [2023-01-31T11:27:24.485208 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Parameters: {"id"=>"bfc28b70-6f1f-4a93-b3bb-9b0447ea1ff3", "branch_uuid"=>"4d86bc56-c477-4c64-9f23-6c3734278398"}
D, [2023-01-31T11:27:24.489820 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", "a727de30-f231-4a76-9823-c1504a052a70"], ["LIMIT", 1]]
I, [2023-01-31T11:27:24.602672 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Metadata API request: [fb-metadata-api-svc-test] GET (0.110 s). Response status: 200
D, [2023-01-31T11:27:24.608408 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendering layout layouts/form.html.erb
D, [2023-01-31T11:27:24.608502 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendering branches/edit.html.erb within layouts/form
D, [2023-01-31T11:27:24.608756 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_error_summary.html.erb (Duration: 0.1ms | Allocations: 81)
D, [2023-01-31T11:27:24.621623 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_expression_answers.html.erb (Duration: 0.6ms | Allocations: 703)
D, [2023-01-31T11:27:24.621854 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_form_expressions.html.erb (Duration: 10.9ms | Allocations: 19126)
I, [2023-01-31T11:27:25.373301 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
D, [2023-01-31T11:27:25.985736 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.3ms | Allocations: 165)
I, [2023-01-31T11:27:26.789491 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:28.188877 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:30.373829 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:33.080026 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:35.174308 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:36.781193 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
I, [2023-01-31T11:27:37.081064 #1]  INFO -- : [104ae818-8d7c-4212-a52a-d6ecc257f4ae] Started GET "/metrics" for 172.20.90.95 at 2023-01-31 11:27:37 +0000
I, [2023-01-31T11:27:37.173220 #1]  INFO -- : [104ae818-8d7c-4212-a52a-d6ecc257f4ae] Processing by MetricsController#show as HTML
I, [2023-01-31T11:27:37.974210 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Exceeded total number of potential routes
D, [2023-01-31T11:27:38.689772 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.1ms | Allocations: 27)
D, [2023-01-31T11:27:38.774430 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_expression_answers.html.erb (Duration: 0.6ms | Allocations: 691)
D, [2023-01-31T11:27:38.774876 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_form_expressions.html.erb (Duration: 84.7ms | Allocations: 9439)
D, [2023-01-31T11:27:38.775436 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.3ms | Allocations: 149)
D, [2023-01-31T11:27:38.775754 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.1ms | Allocations: 25)
D, [2023-01-31T11:27:38.776122 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_form_conditionals.html.erb (Duration: 14165.4ms | Allocations: 3333689)
D, [2023-01-31T11:27:38.776809 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.2ms | Allocations: 149)
D, [2023-01-31T11:27:38.777245 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_destinations_list.html.erb (Duration: 0.1ms | Allocations: 25)
D, [2023-01-31T11:27:38.777567 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/_form.html.erb (Duration: 14167.0ms | Allocations: 3334456)
I, [2023-01-31T11:27:38.778198 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered branches/edit.html.erb within layouts/form (Duration: 14169.6ms | Allocations: 3337380)
D, [2023-01-31T11:27:38.779089 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_head_tags.html.erb (Duration: 0.4ms | Allocations: 159)
D, [2023-01-31T11:27:38.780600 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_properties.html.erb (Duration: 1.2ms | Allocations: 1356)
D, [2023-01-31T11:27:38.782132 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_header.html.erb (Duration: 0.8ms | Allocations: 570)
D, [2023-01-31T11:27:38.782589 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_form_navigation.html.erb (Duration: 0.3ms | Allocations: 217)
D, [2023-01-31T11:27:38.782944 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_footer.html.erb (Duration: 0.1ms | Allocations: 13)
D, [2023-01-31T11:27:38.783388 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_template_dialog.html.erb (Duration: 0.2ms | Allocations: 93)
D, [2023-01-31T11:27:38.783714 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_template_dialog_confirmation.html.erb (Duration: 0.2ms | Allocations: 177)
D, [2023-01-31T11:27:38.784043 #1] DEBUG -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered partials/_template_dialog_confirmation_delete.html.erb (Duration: 0.2ms | Allocations: 177)
I, [2023-01-31T11:27:38.784144 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad]   Rendered layout layouts/form.html.erb (Duration: 14175.7ms | Allocations: 3340997)
I, [2023-01-31T11:27:38.784675 #1]  INFO -- : [98b42f091c9e2f3978ba9690d4ec6cad] Completed 200 OK in 14299ms (Views: 14176.4ms | ActiveRecord: 1.8ms | Allocations: 3355077)
```

Logs of the get request show the allocations still at ~3.4 million but drastically down from 18 million

**Review by H3ll3m4 — APPROVED** [review]
🚀

**Pull request merged**
